### ISSUE TITLE
[speakers.html] CSS UI for Image, Name, Information

### ISSUE THREAD

**Issue by Jiya-Ull-Haq** [GDSC-AEC/RDECS#7]
A page of speakers is to be added. 
Probably I'll be pushing the update with a blank HTML page and the button on the navigation bar.

**fileName:** spreakers.html,
**imageLocations:** "./assets/Images/speakers"
**References:** "**speakers.docx**" is in "**assets**" folder 

**UI Needed:** 
Needed CSS and HTML Cards with Name, Image, Content

**Comment by HarshaSri-Sameera** [comment]
Done!
